### ISSUE TITLE
Files missing for doc build

### ISSUE THREAD

**Issue by chaw** [petercrlane/r7rs-libs#1]
Thanks for putting this together; I'm looking forward to using it.

In trying to build the PDF and HTML docs using the scripts provided, there appear to be a few files missing: 
 - title.pdf
 - summary.txt
 - subdata.txt
 - alldata.txt
I also do not know where to find the html-page-splitter command used by mk-html.sh, though that one may just be a missing package on my system.

On a related note, it would be nice for the docs to be built (perhaps optionally) as part of the main build.  (I'm testing using Kawa and so used build-kawa.sh.)

Regards,

-chaw

**Comment by petercrlane** [comment]
Thanks for taking a look.  I will put some information about building the documentation on the wiki.
(The .txt files are created using create-tables.sps, and html-page-splitter is a separate program I wrote.)
