### ISSUE TITLE
Encoding issue in xml->sxml?

### ISSUE THREAD

**Issue by OpinionatedGeek** [petercrlane/r7rs-libs#5]
Hi there,

Many thanks for your hard work on this project.

I think I've come across a problem when using the slib xml-parse library in Chibi scheme 0.7.3:

`chibi-scheme 0.7.3 "nitrogen" (chibi r7rs ratios complex threads full-unicode modules dynamic-loading bsd macosx little-endian)`

When I try to load from a string containing non-ASCII characters (loaded from an RSS feed), the resultant string values is incorrect.

Here's a sample to reproduce what I mean:

```
(let ((test-string "<title>Sunday: Light Cloud, Maximum Temperature: 15°C (59°F) Minimum Temperature: 10°C (50°F)</title>"))
  (let ((sxml (ssax:xml->sxml  (open-input-string test-string) '())))
    (display (cadadr sxml))
    (newline)))
```

This outputs:

`Sunday: Light Cloud, Maximum Temperature: 15ÂC (59ÂF) Minimum Temperature: 10ÂC (50ÂF)`

As you can see, the degree characters have been replaced with other strange characters.

Is this a known issue? Is it fixable? Or am I just doing something wrong?

Many thanks.

**Comment by petercrlane** [comment]
I think this is to do with the encoding of the input or output ports, and the behaviour of implementations seems to vary.  Sagittarius does the right thing with your sample code.

Larceny produces: 

```
Sunday: Light Cloud, Maximum Temperature: 15�C (59�F) Minimum Temperature: 10�C (50�F)
```

But if I add a transcoder to the output port:

```
(import (scheme base)
        (scheme cxr)
        (scheme write)
        (rnrs io ports)              ;; I don't know if Chibi has an equivalent to this R6RS library?
        (slib xml-parse))

(parameterize ((current-output-port (transcoded-port (standard-output-port)
                                                     (make-transcoder (utf-8-codec)))))
              (let ((test-string "<title>Sunday: Light Cloud, Maximum Temperature: 15°C (59°F) Minimum Temperature: 10°C (50°F)</title>"))
                (let ((sxml (ssax:xml->sxml  (open-input-string test-string) 
                              '())))
                  (display (cadadr sxml))
                  (newline))))
```

I get:

```
$ larceny -r7rs --program test-xml.sps 
Sunday: Light Cloud, Maximum Temperature: 15°C (59°F) Minimum Temperature: 10°C (50°F)
```

I started trying to wrap the input string in a similar way, but that didn't make any difference.

**Comment by OpinionatedGeek** [comment]
Thanks so much for the quick response! I'll ask and see if Chibi has an equivalent to that library yet.

**Comment by OpinionatedGeek** [comment]
Hi,

I have some more details. I thought you might be interested even though the issue is closed.

It looks like it's happening because slib uses (peek) to see what's coming next, and sometimes uses the peeked char instead of the one that's returned by (read).

According to R7RS they should be the same, but there's a problem with Chibi where peek doesn't seem to handle unicode characters properly.

Here's a (completely slib-free) demonstration of the problem in Chibi:

> #!/usr/bin/env chibi-scheme
> 
> (import (scheme small))
> 
> (define (peek-and-read port)
>   (display "Peeked: ")
>   (display (peek-char port))
>   (display ", Read: ")
>   (display (read-char port))
>   (newline)
>   (if (not (eof-object? (peek-char port)))
>     (peek-and-read port))
> )
> 
> (display "Simple peek/read test - show the same character peeked and then read.")
> (newline)
> (peek-and-read (open-input-string "Funny: ¥15°C"))

Here's the output I get:

> Simple peek/read test - show the same character peeked and then read.
> Peeked: F, Read: F
> Peeked: u, Read: u
> Peeked: n, Read: n
> Peeked: n, Read: n
> Peeked: y, Read: y
> Peeked: :, Read: :
> Peeked:  , Read:
> Peeked: Â, Read: ¥
> Peeked: 1, Read: 1
> Peeked: 5, Read: 5
> Peeked: Â, Read: °
> Peeked: C, Read: C

(Most characters are correct, but the Yen and Degree symbols appear corrupt.)

So, you were right - not really an slib problem at all.
